### ISSUE TITLE
Adding ApplicationUser to Product as navigation property

### ISSUE THREAD

**Issue by cptzig** [neozhu/RazorPageCleanArchitecture#98]
Is it possible to add `ApplicationUser` to `src/Domain/Entities/Product.cs` as a navigation property? So that for instance when a new product is created, the product would have the id of the user that did create the product.
Suppose a scenario that I am using this architecture and I want to have ApplicationUser as the user that can make create/edit/delete on the other entities, I tried to do this, but of course I get a circular dependency error because `Application` projects includes `Domain`, and `Infrastructure` includes `Application` application, so if I would include `Infrastructure` in `Domain` a circular dependency error would be raised.
What changes could be done so that the example above would be possible to implement?
Regards. 😊

**Comment by neozhu** [comment]
I have implemented the feature you wanted, please refer to this  project on Github
https://github.com/neozhu/CleanArchitectureWithBlazorServer/tree/navigationIdentityUser
move Identity folder from Infrastructure to Domain Project.
change product class:
````
public class Product : BaseAuditableEntity
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? Brand { get; set; }
    public string? Unit { get; set; }
    public decimal Price { get; set; }
    public IList<string>? Pictures { get; set; }
    [ForeignKey("CreatedBy")]
    public ApplicationUser? CreatedByUser { get; set;}
}

**Comment by DJJones66** [comment]
I haven't fully played with this code yet to explore a different option but if you look at the product as it stands now it is based on the AuditableEntity which does contain data for the CreatedBy.  Maybe can use that to achieve the functionality.

I say this because just moving the Identity folder will probably not go as easily as it sounds.

**Comment by DJJones66** [comment]
> Yes, Your idea is good. I've made it for blazor project https://github.com/neozhu/CleanArchitectureWithBlazorServer

I only asking this here because this is where the conversation is though probably could be in the other project.

Your thoughts on what it would take to use Razor for that project instead of blazor or even as I spoke about above, having both there and merely selecting which one you wish to startup with?  I don't do this enough to do anything other than guess and try but is there any headaches I am missing?
